name: app_ui
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  sizer: ^3.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_gen:
  output: lib/src/generated/ 
# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
  #
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Heavy.ttf
          weight: 800
        - asset: assets/fonts/Avenir-Medium.ttf
          weight: 600
        - asset: assets/fonts/Avenir-Roman.ttf
          weight: 400